### ISSUE TITLE
[Bug] animation.lua regarding Wiki example, here with 'newAnimation'

### ISSUE THREAD

**Issue by ghost** [FloatingBanana/Grove#1]
Foremost, thank you for creating and sharing Grove, providing quite useful functionality! 

When trying out animation.lua with the minimal example given in the Wiki (folder with sample images locally added), I ran into an issue using LÖVE11.4-1:

Error

main.lua:11: attempt to call field 'newAnimation' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
main.lua:11: in function 'load'
[love "callbacks.lua"]:136: in function <[love "callbacks.lua"]:135>
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by FloatingBanana** [comment]
Thank you for the feedback 😄

The example in the wiki was using the wrong constructor which has been removed from the library. I updated the code there to reflect the current api.
